from setuptools import setup, find_packages
setup(
    name="saferelay",
    version="3.6.0",
    description="Zero-trust local DLP for AI-era workflows — 40+ threat patterns across 8+ countries",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="LogicGrid AI, LLC",
    author_email="support@logicgrid.ai",
    url="https://saferelay.ai",
    packages=find_packages(),
    python_requires=">=3.9",
    extras_require={"redis": ["redis>=4.0"]},
    entry_points={"console_scripts": ["saferelay=saferelay.__main__:main"]},
    license="Proprietary",
    keywords="ai-safety api-keys cli dlp pii redaction security zero-trust saferelay",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Topic :: Security",
    ],
)
